import { useRouter } from 'next/router'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { useState } from 'react'

const Home = () => {
  const { push } = useRouter()

  const [phoneNumber, setPhoneNumber] = useState<string>('')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>nao-imobiliarias</h1>

        <p className={styles.description}>
          Para quem está a tentar vender (ou comprar) um imóvel (casa, garagem,
          etc) e é continuamente chatead@ por agentes imboliários.
        </p>

        <form
          onSubmit={e => {
            e.preventDefault()
            push({ pathname: '/[phoneNumber]', query: { phoneNumber } })
          }}
        >
          <label htmlFor="phone-number">Número de telefone/telemóvel</label>
          <input
            type="string"
            name="phone-number"
            id="phone-number"
            onChange={e => setPhoneNumber(e.target.value)}
          />

          <button type="submit">Verificar</button>
        </form>
      </main>

      <footer className={styles.footer}>Cenas</footer>
    </div>
  )
}

export default Home
